### ISSUE TITLE
Language Selection and Dropdown

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/dwbn-registration#1]
This ticket is about adding the manual possibility of changing the language of the registration. For the UI perspective it is a simple language dropdown next to the headline on the right with the language flags. The dropdown maybe similar to the EC Website http://europe-center.org but the currently selected language and flag should be visible from the beginning.

I would also prefer, if we switch the actual translation mechanism to a real i18n via a translate function instead of the current regex replace (because of the better maintainability and the greater flexibility), but lets see what makes sense and can be achieved in a reasonable time.

Thx a lot
Andreas

**Comment by MartinHartnagel** [comment]
Give it a try, just pushed the language-selector. Most likely this needs some Altmühle-config file caressing. And do you know a polish native speaker who could help translating for a dwbn-registration-core/vDev/i18n_pl.php file?

**Comment by Andreas-Schoenefeldt** [comment]
I can ask my girlfriend, let's see what she says.

Best wishes
Andreas

Am 18/05/2015 um 00:09 schrieb Martin Hennig:
